version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '8352:5432'
    networks:
      - ttapp
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 10s
      retries: 5

  ttapp-backend:
    image: ttapp-backend:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
      - APP_HOST=$APP_HOST}
      - AUTHENTICATION_TOKEN_SECRET=${AUTHENTICATION_TOKEN_SECRET}
      - AUTHENTICATION_TOKEN_EXPIRES_IN=${AUTHENTICATION_TOKEN_EXPIRES_IN}
      - REFRESH_AUTHENTICATION_TOKEN_SECRET=${REFRESH_AUTHENTICATION_TOKEN_SECRET}
      - REFRESH_AUTHENTICATION_TOKEN_EXPIRES_IN=${REFRESH_AUTHENTICATION_TOKEN_EXPIRES_IN}
      - STAGE=${STAGE}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_DEV_URL=${FRONTEND_DEV_URL}
      - V2_FRONTEND_DEV_URL=${V2_FRONTEND_DEV_URL}
      - V2_FRONTEND_URL=${V2_FRONTEND_URL}
    ports:
      - '3052:${APP_PORT}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ttapp
    links:
      - db

networks:
  ttapp:
    driver: bridge
