name: Deploy dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd /root/kswbtw/ttapp-backend
          git checkout dev
          git pull
          docker build -f Dockerfile -t ttapp-backend:latest .
          docker compose up -d --force-recreate ttapp-backend
          docker image rm $(docker image ls -a -q)


